### ISSUE TITLE
Errors when running KMC_Lattice_example.exe

### ISSUE THREAD

**Issue by myousefi2016** [MikeHeiber/KMC_Lattice_example#3] opened 2019-01-18 15:12 UTC
I build again the KMC_Lattice_example with GCC 6.3 and OpenMPI 1.10.3 in our cluster and I run the executable by this command: `./KMC_Lattice_example.exe parameters_default.txt`, but I got these errors:

```
Initializing MPI options... MPI initialization complete!
Loading input parameters from file... 
Parameter loading complete!
0: Initializing simulation 0...
Error! The logfile filestream has not been set.
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Error! Simulation object initialization cannot be completed because the input parameters are invalid.
[node1159:183289] *** Process received signal ***
[node1159:183289] Signal: Aborted (6)
[node1159:183289] Signal code:  (-6)
[node1159:183289] [ 0] /lib64/libpthread.so.0(+0xf5d0)[0x2b7ca14ae5d0]
[node1159:183289] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x2b7ca16f12c7]
[node1159:183289] [ 2] /lib64/libc.so.6(abort+0x148)[0x2b7ca16f29b8]
[node1159:183289] [ 3] /software/gcc/6.3.0/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d)[0x2b7ca0c956fd]
[node1159:183289] [ 4] /software/gcc/6.3.0/lib64/libstdc++.so.6(+0x8e6c6)[0x2b7ca0c936c6]
[node1159:183289] [ 5] /software/gcc/6.3.0/lib64/libstdc++.so.6(+0x8e711)[0x2b7ca0c93711]
[node1159:183289] [ 6] /software/gcc/6.3.0/lib64/libstdc++.so.6(+0x8e929)[0x2b7ca0c93929]
[node1159:183289] [ 7] ./KMC_Lattice_example.exe[0x413e81]
[node1159:183289] [ 8] ./KMC_Lattice_example.exe[0x40e77b]
[node1159:183289] [ 9] ./KMC_Lattice_example.exe[0x40a0b7]
[node1159:183289] [10] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2b7ca16dd495]
[node1159:183289] [11] ./KMC_Lattice_example.exe[0x40acdf]
[node1159:183289] *** End of error message ***
Aborted
```

Any idea how to fix them?

**Comment by MikeHeiber** [comment] 2019-01-18 15:16
The execution command must use mpiexec or mpirun.  For example, the standard example in the README is:
```mpiexec -n 10 ./KMC_Lattice_example.exe parameters_default.txt```
You can run on less than 10 cores if you want.  It should not matter.  Let me know if you still get errors.

**Comment by myousefi2016** [comment] 2019-01-18 15:17
I tried that and still same error.

**Comment by MikeHeiber** [comment] 2019-01-18 15:25
Ok this appears to be a bug in the underlying KMC_Lattice submodule.  Essentially, it is complaining the KMC_Lattice_example does not supply a filestream for printing out a log file.  However, KMC_Lattice_example does not enable logging, so this should not be occurring.  The problem is that the default value for enabling logging in KMC_Lattice is not defined in the Parameters_Simulation class header file, so the behavior of running the simulation without setting this parameter is undefined. I will open an issue in KMC_Lattice and set the default value to false, which should hopefully fix this problem.

**Comment by MikeHeiber** [comment] 2019-01-18 16:05
I added default values to all parameters objects in the KMC_Lattice library, and the latest version of KMC_Lattice from the joss-edits branch is now merged into this repo.  Hopefully, this should now resolve your issue.  Please let me know if it works now or if you are still getting errors.

**Comment by myousefi2016** [comment] 2019-01-18 16:09
That fixed the problem and it works fine now!

**Comment by MikeHeiber** [comment] 2019-01-18 16:13
Great to hear!

**Closed as completed by MikeHeiber** 2019-01-18 16:13 UTC
